version: '3.1'

#secrets:
    #secret_file:
    #    file: ip_address.txt

services:
    data_collector:
        build: .
        container_name: data_collector
        restart: always
        ports:
            - '22:22'
        volumes:
            - type: volume
              source: ./volume
              target: /usr/src/script/data

        tty: true
        #secrets:
        #    - secret_file
