version: '3.1'

#secrets:
    #secret_file:
    #    file: ip_address.txt

services:
    influxdb:
        build: .
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        env_file:
            - './influxdb/env.influxdb'
        volumes:
            - type: volume
              source: ./influxdb/data
              target: /var/lib/influxdb

        #secrets:
        #    - secret_file
