version: '3.1'

#secrets:
    #secret_file:
    #    file: ip_address.txt

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        env_file:
            - './influxdb/config/env.influxdb'
        volumes:
            - ./influxdb/data:/var/lib/influxdb
            -./influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql

        #secrets:
        #    - secret_file
