version: '3.1'

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        environment:
            - INFLUXDB_DB=db
#            - INFLUXDB_HTTP_AUTH_ENABLED=true
#            - INFLUXDB_ADMIN_USER=admin
#            - INFLUXDB_ADMIN_PASSWORD=radis
#            - INFLUXDB_USER=python_module
#            - INFLUXDB_USER_PASSWORD=pt3
            - INFLUXDB_DATA_WAL_FSYNC_DELAY=70
        volumes:
            - ./influxdb/data:/var/lib/influxdb

