version: '3.1'
services:
     grafana:
        image: grafana/grafana:5.4.3
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - monitoring
        volumes:
            - grafana-volume:/var/lib/grafana
        environment:
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=smtp.gmail.com:587
            - GF_SMTP_USER=monitoring.nofitication.channel@gmail.com
            - GF_SMTP_PASSWORD=paPayA#47u
            - GF_SMTP_SKIP_VERIFY=true
            - GF_SMTP_FROM_ADDRESS=monitoring.nofitication.channel@gmail.com
            - GF_SMTP_FROM_NAME=Grafana

     influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        networks:
            - monitoring
        ports:
            - 8086:8086
        volumes:
            - influxdb-data-volume:/var/lib/influxdb

networks:
  monitoring:

volumes:
  influxdb-data-volume:
    external: true
  grafana-volume:
    external: true
