version: '3.1'

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        networks:
            - monitoring
        ports:
            - 8086:8086
        volumes:
            - influxdb-data-volume:/var/lib/influxdb

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - monitoring
        volumes:
            - grafana-volume:/var/lib/grafana

networks:
  monitoring:

volumes:
  influxdb-data-volume:
    external: true
  grafana-volume:
    external: true
